Compatibility fixes for newer Python & PyYAML versions
Tested on Python 3.10 & PyYAML 6.0.

Fixes the two errors below:
```
Traceback (most recent call last):
  File "/Users/alp/src/cloud-formation-viz/.venv/bin/cfviz", line 33, in <module>
    sys.exit(load_entry_point('cloud-formation-viz==0.0.1', 'console_scripts', 'cfviz')())
  File "/Users/alp/src/cloud-formation-viz/.venv/lib/python3.10/site-packages/cloud_formation_viz-0.0.1-py3.10.egg/cloud_formation_viz/main.py", line 22, in main
    template = open_cfn(sys.argv)
  File "/Users/alp/src/cloud-formation-viz/.venv/lib/python3.10/site-packages/cloud_formation_viz-0.0.1-py3.10.egg/cloud_formation_viz/main.py", line 43, in open_cfn
    template = yaml.load(text)
TypeError: load() missing 1 required positional argument: 'Loader'
```

```
Traceback (most recent call last):
  File "/Users/alp/src/cloud-formation-viz/.venv/bin/cfviz", line 33, in <module>
    sys.exit(load_entry_point('cloud-formation-viz==0.0.1', 'console_scripts', 'cfviz')())
  File "/Users/alp/src/cloud-formation-viz/.venv/lib/python3.10/site-packages/cloud_formation_viz-0.0.1-py3.10.egg/cloud_formation_viz/main.py", line 24, in main
    (graph, edges) = extract_graph(template.get('Description', ''), template['Resources'])
  File "/Users/alp/src/cloud-formation-viz/.venv/lib/python3.10/site-packages/cloud_formation_viz-0.0.1-py3.10.egg/cloud_formation_viz/main.py", line 76, in extract_graph
    edges.extend(flatten(find_refs(item, details)))
  File "/Users/alp/src/cloud-formation-viz/.venv/lib/python3.10/site-packages/cloud_formation_viz-0.0.1-py3.10.egg/cloud_formation_viz/main.py", line 14, in flatten
    if isinstance(x, collections.Iterable) and not isinstance(el, dict):
AttributeError: module 'collections' has no attribute 'Iterable'
```